### PR TITLE
Reg login

### PR DESCRIPTION
**Pull request by Nejjari001**
- [ ] In this milestone,

- We installed the Devise gem
- We configured Devise for registration and login
- We were able to register and login users

### CODE REVIEW

**Review by rustam-tolipov — COMMENTED** [review]
Hi @Nejjari001, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a descriptive readme. You suppose to use the Microverse template for your readme and personalize it to your project. Kindly add descriptive Readme. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Nejjari001** [comment]
Thank you for your kind review I will make the changes

**Comment by rustam-tolipov** [comment]
Hello Nejjari,
If you are available, could you reply me via slack?

**Review by Kamba56 — COMMENTED** [review]
Hi @Nejjari001

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that **does not properly follow git flow.** You are expected to open a pull request from the `Dev` branch to the `main` branch for your final submission. This way all the changes you implemented from the beginning of the project can be visible in the pull request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
